### PR TITLE
fix(webpack-extraction-plugin): Inject griffel styles in babelPluginStripGriffelRuntime instead of webpackLoader

### PR DESCRIPTION
**Pull request by Dwlad90**
This PR fixes this [issue](https://github.com/microsoft/griffel/issues/154)

### CODE REVIEW

**Comment by Dwlad90** [comment]
Hi @layershifter ,
I made some changes and now extraction works with NextJS. But when I use pnpm workspace and import component from workspace I get an error.

`Error: Final loader (../../node_modules/.pnpm/file+griffel-webpack-extraction-plugin-0.1.4.tgz_md6rzfqrkceubjr2zgohmdxnva/node_modules/@griffel/webpack-extraction-plugin/virtual-loader/index.js) didn't return a Buffer or String`

Maybe do you know the reason for this error?

Working example: [sandbox](https://codesandbox.io/s/keen-jackson-cej9i2?file=/apps/website/pages/index.js)
Example with the error: [sandbox](https://codesandbox.io/s/blissful-matan-tmdnd1?file=/apps/website/pages/index.js)

**Comment by layershifter** [comment]
@Dwlad90 I don't think that it's specific to `pnpm`, I have the same with Yarn:

```js
griffel.css!=!./node_modules/@griffel/webpack-extraction-plugin/virtual-loader/index.js!./node_modules/@griffel/webpack-extraction-plugin/virtual-loader/griffel.css?style=.f1v2re9k%7Bcolor%3Asalmon%3B%7D
Module build failed: Error: Final loader (./node_modules/next/dist/build/webpack/loaders/error-loader.js) didn't return a Buffer or String
    at processResult (/Users/olfedias/WebstormProjects/nextjs-griffel/node_modules/next/dist/compiled/webpack/bundle5.js:49609:17)
    at /Users/olfedias/WebstormProjects/nextjs-griffel/node_modules/next/dist/compiled/webpack/bundle5.js:49695:5
    at /Users/olfedias/WebstormProjects/nextjs-griffel/node_modules/next/dist/compiled/webpack/bundle5.js:141000:3
    at iterateNormalLoaders (/Users/olfedias/WebstormProjects/nextjs-griffel/node_modules/next/dist/compiled/webpack/bundle5.js:140826:10)
    at iterateNormalLoaders (/Users/olfedias/WebstormProjects/nextjs-griffel/node_modules/next/dist/compiled/webpack/bundle5.js:140833:10)
    at /Users/olfedias/WebstormProjects/nextjs-griffel/node_modules/next/dist/compiled/webpack/bundle5.js:140848:3
```

I have it with NPM versions so it's not related to your changes...

**Comment by layershifter** [comment]
> @Dwlad90 I don't think that it's specific to `pnpm`, I have the same with Yarn:
> 
> ```js
> griffel.css!=!./node_modules/@griffel/webpack-extraction-plugin/virtual-loader/index.js!./node_modules/@griffel/webpack-extraction-plugin/virtual-loader/griffel.css?style=.f1v2re9k%7Bcolor%3Asalmon%3B%7D
> Module build failed: Error: Final loader (./node_modules/next/dist/build/webpack/loaders/error-loader.js) didn't return a Buffer or String
>     at processResult (/Users/olfedias/WebstormProjects/nextjs-griffel/node_modules/next/dist/compiled/webpack/bundle5.js:49609:17)
>     at /Users/olfedias/WebstormProjects/nextjs-griffel/node_modules/next/dist/compiled/webpack/bundle5.js:49695:5
>     at /Users/olfedias/WebstormProjects/nextjs-griffel/node_modules/next/dist/compiled/webpack/bundle5.js:141000:3
>     at iterateNormalLoaders (/Users/olfedias/WebstormProjects/nextjs-griffel/node_modules/next/dist/compiled/webpack/bundle5.js:140826:10)
>     at iterateNormalLoaders (/Users/olfedias/WebstormProjects/nextjs-griffel/node_modules/next/dist/compiled/webpack/bundle5.js:140833:10)
>     at /Users/olfedias/WebstormProjects/nextjs-griffel/node_modules/next/dist/compiled/webpack/bundle5.js:140848:3
> ```
> 
> I have it with NPM versions so it's not related to your changes...

Okay, NVM... Looking deeper the issue is indeed solved for NextJS: https://codesandbox.io/s/nervous-zhukovsky-mzq4hs?file=/pages/test.js

Cloning PNPM sandbox...

**Comment by layershifter** [comment]
I reconfigured your original CodeSandbox to use Yarn: https://codesandbox.io/s/relaxed-lake-y0ug39

```
../../node_modules/@griffel/webpack-extraction-plugin/virtual-loader/index.js!../../node_modules/@griffel/webpack-extraction-plugin/virtual-loader/griffel.css?style=.f1l02sjl%7Bheight%3A100%25%3B%7D
An unknown error has occurred
Location: ../../libs/atoms/src/container.js

Import trace for requested module:
../../libs/atoms/src/container.js
../../libs/atoms/index.js
./pages/index.js

../../node_modules/@griffel/webpack-extraction-plugin/virtual-loader/index.js!../../node_modules/@griffel/webpack-extraction-plugin/virtual-loader/griffel.css?style=.f1l02sjl%7Bheight%3A100%25%3B%7D
Module build failed: Error: Final loader (../../node_modules/@griffel/webpack-extraction-plugin/virtual-loader/index.js) didn't return a Buffer or String
    at processResult (/sandbox/node_modules/next/dist/compiled/webpack/bundle5.js:49609:17)
    at /sandbox/node_modules/next/dist/compiled/webpack/bundle5.js:49695:5
    at /sandbox/node_modules/next/dist/compiled/webpack/bundle5.js:141000:3
    at iterateNormalLoaders (/sandbox/node_modules/next/dist/compiled/webpack/bundle5.js:140826:10)
    at iterateNormalLoaders (/sandbox/node_modules/next/dist/compiled/webpack/bundle5.js:140833:10)
    at /sandbox/node_modules/next/dist/compiled/webpack/bundle5.js:140848:3
    at runSyncOrAsync (/sandbox/node_modules/next/dist/compiled/webpack/bundle5.js:140731:12)
    at iterateNormalLoaders (/sandbox/node_modules/next/dist/compiled/webpack/bundle5.js:140844:2)
    at iterateNormalLoaders (/sandbox/node_modules/next/dist/compiled/webpack/bundle5.js:140833:10)
    at /sandbox/node_modules/next/dist/compiled/webpack/bundle5.js:140848:3

Import trace for requested module:
../../libs/atoms/src/container.js
../../libs/atoms/index.js
./pages/index.js


> Build failed because of webpack errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/sandbox/.nvm/versions/node/v14.19.3/bin/node
Arguments: /home/sandbox/.nvm/versions/node/v14.19.3/lib/node_modules/yarn/lib/cli.js build
Directory: /sandbox/apps/website
Output:
```

**Comment by layershifter** [comment]
I also checked current version (0.1.3) and it reproes there, too 🤔

**Comment by layershifter** [comment]
I think that the problem comes from this line:

```
path.pushContainer('body', template.ast(`import "${virtualLoaderPath}!${resourcePath}?style=${params}";`));
```

To invoke custom loader an import should start with `!` (https://webpack.js.org/concepts/loaders/#inline) and error changes then:

```
../../node_modules/@griffel/webpack-extraction-plugin/virtual-loader/index.js!../../node_modules/@griffel/webpack-extraction-plugin/virtual-loader/griffel.css?style=.f1v2re9k%7Bcolor%3Asalmon%3B%7D%0A.fyan362%7Bpadding-left%3A1em%3B%7D%0A.fde2wo7%7Bpadding-right%3A1em%3B%7D
Module parse failed: Unexpected token (1:0)
File was processed with these loaders:
 * ../../node_modules/@griffel/webpack-extraction-plugin/virtual-loader/index.js
You may need an additional loader to handle the result of these loaders.
> .f1v2re9k{color:salmon;}
| .fyan362{padding-left:1em;}
| .fde2wo7{padding-right:1em;}

Import trace for requested module:
./pages/index.js
```

It's not making things easier as we need to specify an extension... So we will return back to `import "griffel.css!=!${virtualLoaderPath}!${resourcePath}?style=${params}";` or `import "${state.filename}.griffel.css!=!${virtualLoaderPath}!${resourcePath}?style=${params}";` and then the problem will be same:

```
./pages/index.js.griffel.css!=!../../node_modules/@griffel/webpack-extraction-plugin/virtual-loader/index.js!../../node_modules/@griffel/webpack-extraction-plugin/virtual-loader/griffel.css?style=.f1v2re9k%7Bcolor%3Asalmon%3B%7D%0A.fyan362%7Bpadding-left%3A1em%3B%7D%0A.fde2wo7%7Bpadding-right%3A1em%3B%7D
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
```

**Comment by Dwlad90** [comment]
> sandbox



> I think that the problem comes from this line:
> 
> ```
> path.pushContainer('body', template.ast(`import "${virtualLoaderPath}!${resourcePath}?style=${params}";`));
> ```
> 
> To invoke custom loader an import should start with `!` (https://webpack.js.org/concepts/loaders/#inline) and error changes then:
> 
> ```
> ../../node_modules/@griffel/webpack-extraction-plugin/virtual-loader/index.js!../../node_modules/@griffel/webpack-extraction-plugin/virtual-loader/griffel.css?style=.f1v2re9k%7Bcolor%3Asalmon%3B%7D%0A.fyan362%7Bpadding-left%3A1em%3B%7D%0A.fde2wo7%7Bpadding-right%3A1em%3B%7D
> Module parse failed: Unexpected token (1:0)
> File was processed with these loaders:
>  * ../../node_modules/@griffel/webpack-extraction-plugin/virtual-loader/index.js
> You may need an additional loader to handle the result of these loaders.
> > .f1v2re9k{color:salmon;}
> | .fyan362{padding-left:1em;}
> | .fde2wo7{padding-right:1em;}
> 
> Import trace for requested module:
> ./pages/index.js
> ```
> 
> It's not making things easier as we need to specify an extension... So we will return back to `import "griffel.css!=!${virtualLoaderPath}!${resourcePath}?style=${params}";` or `import "${state.filename}.griffel.css!=!${virtualLoaderPath}!${resourcePath}?style=${params}";` and then the problem will be same:
> 
> ```
> ./pages/index.js.griffel.css!=!../../node_modules/@griffel/webpack-extraction-plugin/virtual-loader/index.js!../../node_modules/@griffel/webpack-extraction-plugin/virtual-loader/griffel.css?style=.f1v2re9k%7Bcolor%3Asalmon%3B%7D%0A.fyan362%7Bpadding-left%3A1em%3B%7D%0A.fde2wo7%7Bpadding-right%3A1em%3B%7D
> Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
> ```

The reason for this error is the [line](https://github.com/vercel/next.js/blob/0f99768f9811fdf027a083471bd2a435f6207f4a/packages/next/build/webpack/config/blocks/css/index.ts#L311)

We only get the error when doing an import from the workspace, in which case the path to the component is out of next's rootDirectory (/apps/website in our case)

**Comment by Dwlad90** [comment]
I think, specific for  next need to write the next-plugin like [this](https://github.com/seek-oss/vanilla-extract/blob/master/packages/next-plugin/src/index.js).  I tested with @griffel version 0.1.3, it works like a charm.  I will write this instead of changes that I wrote in this PR

**Comment by layershifter** [comment]
> The reason for this error is the [line](https://github.com/vercel/next.js/blob/0f99768f9811fdf027a083471bd2a435f6207f4a/packages/next/build/webpack/config/blocks/css/index.ts#L311)
> 
> We only get the error when doing an import from the workspace, in which case the path to the component is out of next's rootDirectory (/apps/website in our case)

Yeah, I think that you're correct as with imports within workspace it worked.

**Pull request closed without merging**
